name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - 
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL1: https://firmware.meizu.com/Firmware/Flyme/16th/8.1.5.0/cn/20200805093611/1ab62f4b/update.zip
  ROM_NAME: Flyme
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Cleaning up
         run: |
           docker rmi `docker images -q`

       - name: Cloning ErfanGSIs tools
         run: |
            git clone --recurse-submodules https://github.com/SunnySnowYu/ErfanGSIs.git
            sudo chmod -R 777 ErfanGSIs
            curl -sL https://git.io/file-transfer | sh
             
       - name: Setting up Porting Environment
         run: |
           cd ErfanGSIs
           sudo apt update
           sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: |
           sudo ./ErfanGSIs/url2GSI.sh $ROM_URL1 $ROM_NAME
           ls /home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs/ErfanGSIs/output/
           7z a -r raphael-ab.7z /home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs/ErfanGSIs/output/*-AB-10-*-ErfanGSI.img
           sudo ./transfer wet raphael-ab.7z
           sudo rm raphael-ab.7z
           7z a -r raphael-aonly.7z /home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs/ErfanGSIs/output/*-Aonly-*-ErfanGSI.img
           sudo ./transfer wet raphael-aonly.7z
           sudo rm raphael-aonly.7z
           sudo rm -rf /home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs/ErfanGSIs/output

       - name: Download Stock Rom & Generate GSI Part 2
         run: |
           sudo ./ErfanGSIs/url2GSI.sh $ROM_URL2 $ROM_NAME
           7z a -r violet-ab.7z /home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs/ErfanGSIs/output/*-AB-10-*-ErfanGSI.img
           sudo ./transfer wet violet-ab.7z
           sudo rm violet-ab.7z
           7z a -r violet-aonly.7z /home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs/ErfanGSIs/output/*-Aonly-*-ErfanGSI.img
           sudo ./transfer wet violet-aonly.7z
